import dotnetify from 'dotnetify';
import { Element, VMContext, ContextTypes } from './core';
import defaultTheme from './theme-light';
import {
   Alert,
   Button,
   Card,
   Cell,
   CellPanel,
   Checkbox,
   CheckboxGroup,
   Collapsible,
   DataGrid,
   DateField,
   TimeField,
   DateTimeField,
   DropdownList,
   Field,
   Footer,
   Form,
   Frame,
   GridColumn,
   Header,
   Image,
   Label,
   Main,
   Markdown,
   MarkdownText,
   MarkdownTOC,
   Modal,
   MultiselectList,
   Nav,
   NavHeader,
   NavMenu,
   NavMenuTarget,
   NumberField,
   Panel,
   PasswordField,
   RadioGroup,
   RadioToggle,
   Section,
   Tab,
   TabItem,
   TextField,
   TextAreaField,
   Theme,
   withTheme
} from './bootstrap';

let dotNetifyElements = {
   /* Core */
   dotnetify,
   ContextTypes,
   Element,
   VMContext,
   /* Bootstrap */
   Alert,
   Button,
   Card,
   Cell,
   CellPanel,
   Checkbox,
   CheckboxGroup,
   Collapsible,
   DataGrid,
   DateField,
   TimeField,
   DateTimeField,
   DropdownList,
   Field,
   Footer,
   Form,
   Frame,
   GridColumn,
   Header,
   Image,
   Label,
   Main,
   Markdown,
   MarkdownText,
   MarkdownTOC,
   Modal,
   MultiselectList,
   Nav,
   NavHeader,
   NavMenu,
   NavMenuTarget,
   NumberField,
   Panel,
   PasswordField,
   RadioGroup,
   RadioToggle,
   Section,
   Tab,
   TabItem,
   TextField,
   TextAreaField,
   Theme,
   withTheme,
   defaultTheme
};

if (window) window.dotNetifyElements = dotNetifyElements;
export default dotNetifyElements;
